
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:firebase_core/firebase_core.dart';
/// import 'firebase_options.dart';
///
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD37mJZbF10eiAvhH_nUJwF0ip2v7MFMs',
    appId: '1:68464321257:web:6e7034adc0745e14848678',
    messagingSenderId: '68464321257',
    projectId: 'fitness-nutrition-ai',
    authDomain: 'fitness-nutrition-ai.firebaseapp.com',
    storageBucket: 'fitness-nutrition-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD37mJZbF10eiAvhH_nUJwF0ip2v7MFMs',
    appId: '1:68464321257:android:com.fitness.caloriescounter.nutrition.aio.internal',
    messagingSenderId: '68464321257',
    projectId: 'fitness-nutrition-ai',
    storageBucket: 'fitness-nutrition-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD37mJZbF10eiAvhH_nUJwF0ip2v7MFMs',
    appId: '1:68464321257:ios:com.fitness.caloriescounter.nutrition.aio.internal',
    messagingSenderId: '68464321257',
    projectId: 'fitness-nutrition-ai',
    storageBucket: 'fitness-nutrition-ai.firebasestorage.app',
    iosBundleId: 'com.fitness.caloriescounter.nutrition.aio.internal',
  );

    static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD37mJZbF10eiAvhH_nUJwF0ip2v7MFMs',
    appId: '1:68464321257:ios:com.fitness.caloriescounter.nutrition.aio.internal',
    messagingSenderId: '68464321257',
    projectId: 'fitness-nutrition-ai',
    storageBucket: 'fitness-nutrition-ai.firebasestorage.app',
    iosBundleId: 'com.fitness.caloriescounter.nutrition.aio.internal',
  );
}
